---
title: "Data cleaningYG0203"
author: "Yijun Guo"
date: "2025-02-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(cardioStatsUSA)
library(mediation)
library(haven)
library(dplyr)
datapath <- "C:/Users/Yijun/Desktop/datafest/data"
datapath <- "/Users/lizsul/Library/CloudStorage/OneDrive-DrexelUniversity/ENAR datafest/Data"
```

# Load cardiostat data
```{r echo=FALSE}
nhanes <- as.data.frame(nhanes_data)

# Change the ID name to match external data
colnames(nhanes)[1] <- "SEQN" 

# Load variable of interest:
nhanes_sub <- nhanes %>%
  dplyr::select(SEQN,
         svy_weight_mec,
         svy_psu,
         svy_strata,
         svy_year,
         svy_subpop_htn,
         bp_control_jnc7,
         bp_med_n_pills,
         demo_race,
         demo_age_cat,
         demo_gender,
         cc_smoke,
         cc_diabetes,
         cc_cvd_any)%>%
  rename(bp_control = bp_control_jnc7,
         medication = bp_med_n_pills,
         race_ethnicity = demo_race,
         age_cat = demo_age_cat,
         gender = demo_gender,
         smoke = cc_smoke,
         diabetes = cc_diabetes,
         cvd = cc_cvd_any)%>%
  filter(svy_subpop_htn == 1,
         svy_year %in% c("2013-2014","2015-2016","2017-2020"))


nhanes_sub[nhanes_sub$svy_year == "2013-2014",]
```

# Load external data
```{r}
###############################  Data from 2013-2014 #############################
## Demographic: Select education level, marital status, ratio of family income to poverty 
library(dplyr)
select <- dplyr::select
demo13_14 <- read_xpt(file.path(datapath, "2013-2014", "DEMO_H.XPT"))
demo13_14_sub <- demo13_14 %>% select(SEQN, DMDEDUC2, DMDMARTL, INDFMPIR, WTINT2YR, WTMEC2YR)

## Depression level: Scores of PHQ-9 questionnaire
dpq13_14 <- read_xpt(file.path(datapath, "2013-2014", "DPQ_H.XPT"))
dpq13_14_sub <- dpq13_14 %>% select(SEQN,starts_with("DPQ")) %>% select(-DPQ100)

## Healthcare accessibility: Select health insurance coverage, access to healthcare
hiq13_14 <- read_xpt(file.path(datapath, "2013-2014", "HIQ_H.XPT"))
hiq13_14_sub <- hiq13_14 %>% select(SEQN,HIQ011)

huq13_14 <- read_xpt(file.path(datapath, "2013-2014", "HUQ_H.XPT"))
huq13_14_sub <- huq13_14 %>% select(SEQN,HUQ030)

ext13_14 <- demo13_14_sub %>%
  full_join(dpq13_14_sub, by = "SEQN") %>%
  full_join(hiq13_14_sub, by = "SEQN")%>%
  full_join(huq13_14_sub, by = "SEQN")%>%
  mutate(svy_year = "2013-2014")

###############################  Data from 2015-2016 #############################
## Demographic 
demo15_16 <- read_xpt(file.path(datapath, "2015-2016", "DEMO_I.XPT"))
demo15_16_sub <- demo15_16 %>% select(SEQN, DMDEDUC2, DMDMARTL, INDFMPIR, WTINT2YR, WTMEC2YR)

## Depression level 
dpq15_16 <- read_xpt(file.path(datapath, "2015-2016", "DPQ_I.XPT"))
dpq15_16_sub <- dpq15_16 %>% select(SEQN,starts_with("DPQ"))%>% select(-DPQ100)

## Healthcare accessibility
hiq15_16 <- read_xpt(file.path(datapath, "2015-2016", "HIQ_I.XPT"))
hiq15_16_sub <- hiq15_16 %>% select(SEQN,HIQ011)

huq15_16 <- read_xpt(file.path(datapath, "2015-2016", "HUQ_I.XPT"))
huq15_16_sub <- huq15_16 %>% select(SEQN,HUQ030)

ext15_16 <- demo15_16_sub %>%
  full_join(dpq15_16_sub, by = "SEQN") %>%
  full_join(hiq15_16_sub, by = "SEQN")%>%
  full_join(huq15_16_sub, by = "SEQN")%>%
  mutate(svy_year = "2015-2016")

###############################  Data from 2017-2020 #############################
## Demographic
demo17_20 <- read_xpt(file.path(datapath, "2017-2020", "P_DEMO.XPT"))
demo17_20_sub <- demo17_20 %>% 
  select(SEQN, DMDEDUC2, DMDMARTZ, INDFMPIR, WTINTPRP, WTMECPRP)%>%
  rename(DMDMARTL = DMDMARTZ) %>%
  rename(WTINT2YR = WTINTPRP, WTMEC2YR = WTMECPRP)
# Variable name changed in 2017-2020 cycle

## Depression level
dpq17_20 <- read_xpt(file.path(datapath, "2017-2020", "P_DPQ.XPT"))
dpq17_20_sub <- dpq17_20 %>% select(SEQN,starts_with("DPQ"))%>% select(-DPQ100)

## Healthcare accessibility
hiq17_20 <- read_xpt(file.path(datapath, "2017-2020", "P_HIQ.XPT"))
hiq17_20_sub <- hiq17_20 %>% select(SEQN,HIQ011)

huq17_20 <- read_xpt(file.path(datapath, "2017-2020", "P_HUQ.XPT"))
huq17_20_sub <- huq17_20 %>% select(SEQN,HUQ030)

ext17_20 <- demo17_20_sub %>%
  full_join(dpq17_20_sub, by = "SEQN") %>%
  full_join(hiq17_20_sub, by = "SEQN")%>%
  full_join(huq17_20_sub, by = "SEQN")%>%
  mutate(svy_year = "2017-2020")

# alcohol use
setwd("/Users/lizsul/Library/CloudStorage/OneDrive-DrexelUniversity/ENAR datafest/Data")
alq_13 <- read_xpt("2013-2014/ALQ_H.xpt") %>% mutate(svy_year = "2013-2014") %>% select(SEQN,ALQ101)
alq_15 <- read_xpt("2015-2016/ALQ_I.xpt") %>% mutate(svy_year = "2015-2016") %>% select(SEQN,ALQ101)
alq_17 <- read_xpt("2017-2020/P_ALQ.xpt") %>% 
  mutate(svy_year = "2017-2020") %>% 
  mutate(ALQ101 = case_when(
    ALQ121 %in% c(0,8,9,10) ~ 2, # No
    ALQ121 %in% c(1:7) ~ 1,
    ALQ121 %in% c(77,99,NA) ~ NA,
  )) %>%  select(SEQN,ALQ101)
#alq_21 <- read_xpt("2021-2023/ALQ_L.xpt") %>% mutate(svy_year = "2021-2023") %>% select(SEQN,ALQ101)

# physical activity
paq_13 <- read_xpt("2013-2014/PAQ_H.xpt") %>% mutate(svy_year = "2013-2014") %>% select(SEQN, PAQ650,PAD680)
paq_15 <- read_xpt("2015-2016/PAQ_I.xpt") %>% mutate(svy_year = "2015-2016") %>% select(SEQN, PAQ650,PAD680)
paq_17 <- read_xpt("2017-2020/P_PAQ.xpt") %>% mutate(svy_year = "2017-2020") %>% select(SEQN, PAQ650,PAD680)
#paq_21 <- read_xpt("2021-2023/PAQ_L.xpt") %>% mutate(svy_year = "2021-2023") %>% select(SEQN, PAQ650,PAD680)

# dietary
dr1_13 <- read_xpt("2013-2014/DR1TOT_H.xpt") %>% mutate(svy_year = "2013-2014") %>% select(SEQN, DR1TSODI, WTDRD1)
dr1_15 <- read_xpt("2015-2016/DR1TOT_I.xpt") %>% mutate(svy_year = "2015-2016") %>% select(SEQN, DR1TSODI, WTDRD1)
dr1_17 <- read_xpt("2017-2020/P_DR1TOT.xpt") %>% 
  mutate(svy_year = "2017-2020") %>% 
  rename(WTDRD1 = WTDRD1PP) %>%
  select(SEQN, DR1TSODI, WTDRD1) 
dr1_21 <- read_xpt("2021-2023/DR1TOT_L.xpt") %>% mutate(svy_year = "2021-2023") %>% select(SEQN, DR1TSODI, WTDRD1)
```

```{r}
# Merge the data with nhanes data
library(purrr)
ext13_14_f <- ext13_14 %>%
  left_join(alq_13, by = "SEQN") %>%
  left_join(paq_13, by = "SEQN") %>%
  left_join(dr1_13, by = "SEQN")
ext15_16_f <- ext15_16 %>%
  left_join(alq_15, by = "SEQN") %>%
  left_join(paq_15, by = "SEQN") %>%
  left_join(dr1_15, by = "SEQN")
ext17_20_f <- ext17_20 %>%
  left_join(alq_17, by = "SEQN") %>%
  left_join(paq_17, by = "SEQN") %>%
  left_join(dr1_17, by = "SEQN")
ext_comb <- rbind(ext13_14_f,ext15_16_f,ext17_20_f)
nhanes_comb <- nhanes_sub%>%
  left_join(ext_comb,by = c("svy_year","SEQN"))

```

# Data pre-processing
```{r}
# Generate the depression category with total PHQ-9 score
## For one missing question, impute with average value
## For two or more missing, the total score is missing
nhanes_comb$total_PHQ9 <- NA
for (i in 1:nrow(nhanes_comb)){
  DPQ <- nhanes_comb[i,]
  DPQ <- DPQ %>% select(starts_with("DPQ"))
  n_answered <-sum(!is.na(DPQ))
  if (n_answered < 8){
    nhanes_comb$total_PHQ9[i] <- NA
  }
  else if (n_answered == 8){
    avg <- sum(DPQ[!is.na(DPQ)])/8
    nhanes_comb$total_PHQ9[i] <- avg*9
  }
  else if (n_answered == 9){
    nhanes_comb$total_PHQ9[i] <- sum(DPQ)
  }
}


nhanes_comb$phq9_cat <- ifelse(nhanes_comb$total_PHQ9>=1&nhanes_comb$total_PHQ9<=4,"Minimal depression",
                               ifelse(nhanes_comb$total_PHQ9>=5&nhanes_comb$total_PHQ9<=9,"Mild depression",
                                      ifelse(nhanes_comb$total_PHQ9>=10&nhanes_comb$total_PHQ9<=14,"Moderate depression",
                                             ifelse(nhanes_comb$total_PHQ9>=15&nhanes_comb$total_PHQ9<=19,"Moderately severe depression",
                                                    ifelse(nhanes_comb$total_PHQ9>=20&nhanes_comb$total_PHQ9<=27,"Severe depression",                                                                                                         ifelse(nhanes_comb$total_PHQ9==0,"No depression",NA))))))


nhanes_comb<-nhanes_comb%>%
  select(-starts_with("DPQ"),-total_PHQ9)


colSums(is.na(nhanes_comb))
colSums(is.na(nhanes_comb)/nrow(nhanes_comb))*100
saveRDS(nhanes_comb,file = "nhanes_comb1.rda")


```

